spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poliglota_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: sensores
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

    
  mongodb:
    uri: mongodb://localhost:27017/poliglota_mongo


# ðŸ“˜ Swagger / OpenAPI configuration
springdoc:
  packages-to-scan: com.example.persistencia.poliglota.controller
  paths-to-match: /api/**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
